### ISSUE TITLE
Embeded fonts in EPUB format

### ISSUE THREAD

**Issue by Nikolay-Ch** [rupor-github/fb2converter#12]
It is useful to create EPUB files with embedded fonts. Like fb2mobi do.

**Comment by rupor-github** [comment]
It is useful indeed. And supported from the day one too. I hope you could visit [forum](https://4pda.to/forum/index.php?showtopic=942250) for examples (use search function).

**Comment by Nikolay-Ch** [comment]
Can you please give me a link to message, where described about this option?
In FB2Mobi I check one checkbox and viola, all works.

But what I need to do in Fb2C? Change css-file? But I don't have this file.
Is there any example of css-file with embedded font?

**Comment by rupor-github** [comment]
fb2c supports "export" command which provides access to all configuration and profile information you can customize and use later. You need to read "usage" information which is being printed when you run fb2c or read forum (link provided above) or both. There is no UI in fb2c nut otherwise id does pretty much what fb2mobi does and in a similar way. Using "search" for the word "font" in a forum you will get [examples](https://4pda.to/forum/index.php?showtopic=942250&view=findpost&p=115910531) and discussions.
