### ISSUE TITLE
Where can I find the <transfer> function?

### ISSUE THREAD

**Issue by CuteLicense** [rupor-github/fb2converter#18]
> NAME:
>    fb2c.exe transfer - Prepares EPUB file(s) for transfer (Kindle only!)

Doesn't the new version written in Go support transfer commands?
Are there any plans to add this feature? Or where can I find and use this feature? Thanks.

**Comment by rupor-github** [comment]
Due to the changes in how Amazon handles mobi and epub files "transfer" command has been removed in version 1.62.0 and "send to kindle" support has been switched from mobi to epub files. All functionality for "preparing" epub files has been retired at the same time - it was added purely to simplify delivery of epub files to kindles and now that Amazon supports it directly is not needed any more.  Presently there are no plans to re-introduce it.
