### ISSUE TITLE
Invalid epub generated

### ISSUE THREAD

**Issue by asm0dey** [rupor-github/fb2converter#25]
The epubs, generated by the software fail validation on both https://draft2digital.com/book/epubcheck/upload and local epubcheck.

Could you please fix the errors?

Here is the example file, renamed to zip for GitHub to accept it
[129374.zip](https://github.com/user-attachments/files/17994088/129374.zip)

**Comment by rupor-github** [comment]
I am only aware of 2 "errors" from epubcheck (it has been pretty consistent across multiple epubcheck versions for many years):

1. ERROR(RSC-005): 129374.epub/OEBPS/content.opf(3,5494): Error while parsing file: attribute "properties" not allowed here; expected attribute "fallback", "fallback-style", "required-modules" or "required-namespace"
2. ERROR(RSC-005): 129374.epub/OEBPS/content.opf(3,5839): Error while parsing file: attribute "page-map" not allowed here; expected attribute "id"

Both are intentional and to a degree historical:
The first one is "preferred" method of specifying cover according to latest Amazon publishing guidelines I worked with:
![image](https://github.com/user-attachments/assets/2abca338-1c43-423b-a4e8-16d4ffcd50b7)

The second comes as the result of users request to support "real" pages in the epubs used to generate Kindle content. It breaks epub2 spec similar to the first (both are covered by epub3 I believe). It is possible to switch it on/off using special switch, but so far I am unaware of any particular harm of always having page map included in epub2.

Do you observe any undesired behaviors with any readers or software you are using? if so - could you please share any details?
